import type { Article } from "./types.js";

/** 计算相对时间描述 */
function relativeTime(date: Date, now: Date): string {
  const diffMs = now.getTime() - date.getTime();
  const diffMin = Math.floor(diffMs / 60000);
  const diffHr = Math.floor(diffMs / 3600000);
  const diffDay = Math.floor(diffMs / 86400000);

  if (diffMin < 1) return "刚刚";
  if (diffMin < 60) return `${diffMin}分钟前`;
  if (diffHr < 24) return `${diffHr}小时前`;
  if (diffDay < 7) return `${diffDay}天前`;
  // 超过7天显示日期
  return formatDate(date);
}

/** 格式化日期为 YYYY-MM-DD */
function formatDate(date: Date): string {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, "0");
  const d = String(date.getDate()).padStart(2, "0");
  return `${y}-${m}-${d}`;
}

/** 格式化时间为 HH:MM */
function formatTime(date: Date): string {
  return `${String(date.getHours()).padStart(2, "0")}:${String(date.getMinutes()).padStart(2, "0")}`;
}

/** 格式化完整时间 HH:MM YYYY-MM-DD */
function formatDateTime(date: Date): string {
  return `${formatTime(date)} ${formatDate(date)}`;
}

/** 生成 Markdown 日报 */
export function generateReport(
  articles: Article[],
  options?: { nextRunTime?: string },
): string {
  const now = new Date();
  const sourceStats = new Map<string, number>();

  for (const a of articles) {
    sourceStats.set(a.source, (sourceStats.get(a.source) ?? 0) + 1);
  }

  const totalArticles = articles.length;
  const totalSources = sourceStats.size;

  const lines: string[] = [];

  // 头部
  lines.push("# 🤖 AI 新闻日报");
  lines.push("");
  lines.push(
    `**日期**: ${formatDate(now)} | **生成时间**: ${formatTime(now)} CST`,
  );
  lines.push("");

  // 统计摘要
  const sourceDetails = [...sourceStats.entries()]
    .map(([src, count]) => `${src}: ${count}篇`)
    .join(" | ");
  lines.push(
    `> 📊 共收录 **${totalArticles}** 篇，来自 **${totalSources}** 个源 | ${sourceDetails}`,
  );
  lines.push("");

  lines.push("---");
  lines.push("");

  // 文章表格
  if (articles.length === 0) {
    lines.push("> ⚠️ 暂无文章");
    lines.push("");
  } else {
    lines.push("| 时间 | 相对 | 标题 & 摘要 | 来源 |");
    lines.push("|------|------|-------------|------|");

    for (const article of articles) {
      const timeStr = formatDateTime(article.pubDate);
      const relStr = relativeTime(article.pubDate, now);

      // 构建双语标题行
      let titleCell = `[${escapeMd(article.title)}](${article.link})`;
      if (article.titleZh) {
        titleCell += `<br>🇨🇳 ${escapeMd(article.titleZh)}`;
      }

      // 构建双语摘要行
      const summaryParts: string[] = [];
      if (article.summary) {
        summaryParts.push(`<small>📝 ${escapeMd(article.summary)}</small>`);
      }
      if (article.summaryZh) {
        summaryParts.push(`<small>🇨🇳 ${escapeMd(article.summaryZh)}</small>`);
      }
      if (summaryParts.length > 0) {
        titleCell += "<br>" + summaryParts.join("<br>");
      }

      const sourceLabel = `\`${escapeMd(article.source)}\``;

      lines.push(`| ${timeStr} | ${relStr} | ${titleCell} | ${sourceLabel} |`);
    }

    lines.push("");
  }

  lines.push("---");
  lines.push("");

  // 尾部
  if (options?.nextRunTime) {
    lines.push(`> 📬 定时模式运行中，下一篇日报: ${options.nextRunTime}`);
    lines.push("");
  }

  lines.push(
    `> 🤖 Generated by AI News Digest at ${formatDateTime(now)}`,
  );

  return lines.join("\n");
}

/** 对 Markdown 特殊字符做转义 */
function escapeMd(text: string): string {
  return text
    .replace(/\\/g, "\\\\")
    .replace(/\|/g, "\\|")
    .replace(/\n/g, " ")
    .replace(/\r/g, "");
}
